const CFG={url:'https://qzsuqxgsnzmmzzwujhps.supabase.co',key:'sb_publishable_aF3Tmp_V4yHaop8j9Hu4BA_nB8YEU9O',quiz:'afm-master',feedback:'https://docs.google.com/forms/d/e/1FAIpQLSdN2TbASV9tvzUfvImDBDD3XHRE4JWsU6m5YCK7eLDU5wZ-nQ/viewform?usp=publish-editor',source:'https://cadivyanshu.github.io/AFM/questions.js'};
const db=window.supabase.createClient(CFG.url,CFG.key);
let S={student:null,attempt:null,questions:[],i:0,answers:{},started:Date.now(),questionStarted:Date.now(),timer:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sec=n=>{n=Math.max(0,Math.floor(n||0));return String(Math.floor(n/3600)).padStart(2,'0')+':'+String(Math.floor(n/60)%60).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};
function brand(){return '<div class="brand"><div><div class="brand-mark">VP<i>:</i>C</div><div class="brand-sub">VINIJYN PRO CLASSES</div></div></div>'}
function login(){document.body.innerHTML='<div class="login-wrap"><section class="login-card">'+brand()+'<h1>Welcome to VPC AFM</h1><p class="muted">Your progress is saved automatically. Return anytime and continue where you stopped.</p><div class="notice">Use the same mobile number whenever you return.</div><form id="login"><label>Full name</label><input name="name" required minlength="2" placeholder="Your name"><label>Mobile number</label><input name="phone" required inputmode="tel" placeholder="Your mobile number"><label>City / Place</label><input name="place" required minlength="2" placeholder="Your city or place"><button class="btn" style="width:100%;margin-top:20px">Start / Continue Learning</button></form><p id="err" class="muted"></p></section></div>';
$('#login').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||'').trim(),place=String(f.get('place')||'').trim();if(phone.replace(/\D/g,'').length<7)return $('#err').textContent='Please enter a valid mobile number.';$('#err').textContent='Setting up your learning session…';let {data,error}=await db.rpc('register_or_resume_student',{p_name:name,p_phone:phone,p_place:place});if(error)return $('#err').textContent=error.message;S.student=data;localStorage.vpcPhone=phone;localStorage.vpcName=name;localStorage.vpcPlace=place;await bootQuiz();};}
async function loadQuestions(){try{let r=await fetch(CFG.source,{cache:'no-store'});if(!r.ok)throw Error('Question bank unavailable');let t=await r.text();
let m=t.match(/window\.AFM_MCQS_QUESTIONS\s*=\s*(\[[\s\S]*\]);?\s*$/);let raw=m?JSON.parse(m[1]):null;
if(!Array.isArray(raw))throw Error('Question array not detected');
return raw.map((q,i)=>({id:String(q.id??q.questionId??i+1),text:q.question??q.text??q.questionText??'',options:Array.isArray(q.options)?q.options:(q.answers??[]),correct:Number(q.correctAnswer??q.correct??q.answer??q.correctOption??-1),caseText:q.passage??q.caseScenarioText??'',caseId:String(q.caseScenarioNum??q.caseId??q.caseNumber??q.scenarioId??''),caseTitle:q.caseScenarioTitle??'',raw:q}));
}catch(e){console.error('Question load failed:',e);return []}}
async function bootQuiz(){S.questions=await loadQuestions();if(!S.questions.length){document.body.innerHTML='<div class="login-wrap"><section class="login-card">'+brand()+'<h1>Question bank could not be loaded</h1><p class="muted">The VPC application loaded, but the AFM question bank could not be read from the original deployment.</p><p class="notice">Please refresh once. If the problem remains, the question-bank source needs to be copied into this repository.</p></section></div>';return}
let {data,error}=await db.rpc('resume_attempt',{p_phone:S.student.phone,p_quiz_key:CFG.quiz});if(error){alert(error.message);return}S.attempt=data;S.i=Math.min(data.current_question_index||0,S.questions.length-1);let a=await db.rpc('load_attempt_answers',{p_phone:S.student.phone,p_attempt_id:S.attempt.id});if(!a.error)(a.data||[]).forEach(x=>S.answers[x.question_id]=x);S.started=Date.now()-(data.total_seconds||0)*1000;S.questionStarted=Date.now();render();}
function answerState(q){return S.answers[q.id]||{attempt_id:S.attempt?.id,question_id:q.id,question_index:S.i,selected_option:null,correct_option:q.correct,skipped:false,marked_for_review:false,hidden_options:[],used_5050:false,used_expert:false,used_poll:false,seconds_spent:0}}
function optionClass(a,j){let c='option';if(a.selected_option===j)c+=' selected';if((a.hidden_options||[]).includes(j))c+=' hidden';return c;}
function render(){let q=S.questions[S.i];if(!q)return;let a=answerState(q);if(S.timer)clearInterval(S.timer);document.body.innerHTML='<div class="shell"><header class="topbar">'+brand()+'<div class="title">CA Final · Advanced Financial Management</div><div class="header-actions"><span id="clock">'+sec((Date.now()-S.started)/1000)+'</span><button class="btn alt" id="caseBtn">Case Jump</button><button class="btn gold" id="analysisBtn">📊 Analysis</button></div></header><main class="main"><section class="card"><div class="meta"><span>Question '+(S.i+1)+' of '+S.questions.length+'</span><span id="saved">☁ Saved</span></div>'+(q.caseText?'<div class="case"><strong>'+(esc(q.caseTitle||('Case Scenario '+q.caseId)))+'</strong><div>'+esc(q.caseText)+'</div></div>':'')+'<div class="question">'+esc(q.text)+'</div><div class="options">'+q.options.map((o,j)=>'<button class="'+optionClass(a,j)+'" data-opt="'+j+'"><b>'+String.fromCharCode(65+j)+'.</b> '+esc(typeof o==='object'?(o.text??o.label??JSON.stringify(o)):o)+'</button>').join('')+'</div><div class="nav"><div><button class="btn alt" id="prev">← Previous</button> <button class="btn alt" id="skip">Skip</button></div><div><button class="btn alt" id="mark">'+(a.marked_for_review?'★ Marked':'☆ Mark')+'</button> <button class="btn" id="next">'+(S.i===S.questions.length-1?'Finish':'Next →')+'</button></div></div><div class="feedback"><b>Need a quick check on your progress?</b><br><span class="muted">Analysis is available at any time and your work is auto-saved.</span></div></section><aside class="card side"><div class="panel-title"><h3>Question Palette</h3><button class="btn alt" id="saveNow">Save now</button></div><div class="palette">'+S.questions.map((x,j)=>'<button class="qdot '+status(x,j)+'" data-go="'+j+'">'+(j+1)+'</button>').join('')+'</div><hr><h3>Live status</h3>'+statsHTML()+'</aside></main></div>';
document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>choose(+b.dataset.opt));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{S.i=+b.dataset.go;S.questionStarted=Date.now();render()});$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#skip').onclick=()=>skip();$('#mark').onclick=()=>toggleMark();$('#analysisBtn').onclick=analysis;$('#caseBtn').onclick=caseJump;$('#saveNow').onclick=save;S.timer=setInterval(()=>{let c=$('#clock');if(c)c.textContent=sec((Date.now()-S.started)/1000)},1000);}
function status(q,j){let a=S.answers[q.id];if(j===S.i)return 'current';if(!a)return '';if(a.marked_for_review)return 'marked';if(a.skipped)return 'skipped';if(a.selected_option===null||a.selected_option===undefined)return '';return a.is_correct?'correct':'wrong'}
function stats(){let v=Object.values(S.answers),answered=v.filter(a=>a.selected_option!==null&&a.selected_option!==undefined),correct=answered.filter(a=>a.is_correct).length;return {attempted:answered.length,correct,wrong:answered.length-correct,skipped:v.filter(a=>a.skipped).length,accuracy:answered.length?Math.round(correct/answered.length*100):0,time:Math.floor((Date.now()-S.started)/1000)}}
function statsHTML(){let x=stats();return '<div class="progress-grid"><div class="stat"><b>'+x.attempted+'</b>Attempted</div><div class="stat"><b>'+x.accuracy+'%</b>Accuracy</div><div class="stat"><b>'+x.correct+'</b>Correct</div><div class="stat"><b>'+sec(x.time)+'</b>Time</div></div>'}
async function choose(j){let q=S.questions[S.i],a=answerState(q);a.selected_option=j;a.correct_option=q.correct;a.is_correct=j===q.correct;a.skipped=false;a.question_index=S.i;a.seconds_spent=Math.floor((a.seconds_spent||0)+(Date.now()-S.questionStarted)/1000);S.questionStarted=Date.now();S.answers[q.id]=a;await saveAnswer(a);render()}
async function skip(){let q=S.questions[S.i],a=answerState(q);a.skipped=true;a.question_index=S.i;a.seconds_spent=Math.floor((a.seconds_spent||0)+(Date.now()-S.questionStarted)/1000);S.answers[q.id]=a;await saveAnswer(a);await move(1)}
async function toggleMark(){let q=S.questions[S.i],a=answerState(q);a.marked_for_review=!a.marked_for_review;S.answers[q.id]=a;await saveAnswer(a);render()}
async function move(n){await save();if(n>0&&S.i===S.questions.length-1)return finish();S.i=Math.max(0,Math.min(S.questions.length-1,S.i+n));S.questionStarted=Date.now();render()}
async function saveAnswer(a){let {error}=await db.rpc('save_attempt_answer',{p_phone:S.student.phone,p_attempt_id:S.attempt.id,p_question_id:a.question_id,p_question_index:a.question_index,p_selected_option:a.selected_option,p_correct_option:a.correct_option,p_is_correct:a.is_correct,p_skipped:a.skipped,p_marked:a.marked_for_review,p_hidden_options:a.hidden_options||[],p_used_5050:a.used_5050,p_used_expert:a.used_expert,p_used_poll:a.used_poll,p_seconds_spent:Math.floor(a.seconds_spent||0)});if(error)console.error('Answer save failed:',error)}
async function save(status='active'){if(!S.attempt||!S.questions.length)return;let q=S.questions[S.i];let {error}=await db.rpc('save_attempt_progress',{p_phone:S.student.phone,p_attempt_id:S.attempt.id,p_current_index:S.i,p_current_question_id:q.id,p_total_seconds:Math.floor((Date.now()-S.started)/1000),p_status:status});let x=$('#saved');if(x)x.textContent=error?'⚠ Save issue':'☁ Saved just now'}
function closeModal(){let m=$('#modal');if(m)m.remove()}
function analysis(){let x=stats();document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal"><div class="modal-box"><button class="close" id="closeAnalysis">✕</button><h2>Live Performance Analysis</h2><div class="progress-grid"><div class="stat"><b>'+x.attempted+'</b>Attempted</div><div class="stat"><b>'+x.correct+'</b>Correct</div><div class="stat"><b>'+x.wrong+'</b>Wrong</div><div class="stat"><b>'+x.skipped+'</b>Skipped</div><div class="stat"><b>'+x.accuracy+'%</b>Accuracy</div><div class="stat"><b>'+sec(x.time)+'</b>Total time</div></div><h3>Time management</h3><p class="muted">Average time per attempted question: '+(x.attempted?sec(x.time/x.attempted):'00:00:00')+'</p><button class="btn" id="backAnalysis">Back to quiz</button></div></div>');$('#closeAnalysis').onclick=closeModal;$('#backAnalysis').onclick=closeModal}
function caseJump(){let q=S.questions[S.i],id=q.caseId;if(!id){alert('This question is not currently linked to a multi-question case scenario.');return}let list=S.questions.map((x,i)=>({x,i})).filter(z=>z.x.caseId===id);document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal"><div class="modal-box"><button class="close" id="closeCase">✕</button><h2>Jump within this case scenario</h2><p class="muted">Choose any question from the current case.</p><div class="case-jump">'+list.map(z=>'<button data-casego="'+z.i+'">Question '+(z.i+1)+'</button>').join('')+'</div></div></div>');$('#closeCase').onclick=closeModal;document.querySelectorAll('[data-casego]').forEach(b=>b.onclick=()=>{S.i=+b.dataset.casego;S.questionStarted=Date.now();closeModal();render()})}
async function finish(){await save('completed');let x=stats();document.body.innerHTML='<div class="shell"><div class="card empty">'+brand()+'<h1>Attempt completed 🎉</h1><p class="muted">You attempted '+x.attempted+' questions with '+x.accuracy+'% accuracy in '+sec(x.time)+'.</p><button class="btn gold" id="feedback">⭐ Share your feedback</button><p><button class="btn alt" id="review">Review analysis</button></p></div></div>';$('#feedback').onclick=()=>window.open(CFG.feedback,'_blank','noopener');$('#review').onclick=analysis}
(async()=>{let p=localStorage.vpcPhone;if(p){S.student={phone:p,name:localStorage.vpcName,place:localStorage.vpcPlace};await bootQuiz()}else login()})();